version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: whiteboard-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # ← именованный volume
    restart: unless-stopped

# Объявление томов
volumes:
  pgdata:  # Docker сам создаст и управляет им